version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: TodoApp.Api/Dockerfile
    container_name: todo-backend
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/tasks.db
    volumes:
      - sqlite-data:/app/data

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_GRAPHQL_URL=http://backend:5000/graphql
    depends_on:
      - backend

volumes:
  sqlite-data: 